### PR TITLE
Allow SDC `get_*` with 0 args and on object references

### PR DESCRIPTION
**Pull request by akashlevy**
This PR adds two features into SDC processing:
- `get_*` with no arguments is interpreted as `get_* *`
- `get_*` called on SWIG object references `*_p_<objtype>` will keep those references intact rather than failing

Let me know if anything should be added to the docs for these changes.

### CODE REVIEW

**Comment by jjcherry56** [comment]
You need to type check the objects:
get_pins [get_cells]
_e001650300600000_p_Instance _8001650300600000_p_Instance _6000650300600000_p_Instance _2001650300600000_p_Instance _c000650300600000_p_Instance

I would prefer it if you did not use continue.
Please break the tests into 2 tests; one for no arg and the other for passing objects.

**Comment by akashlevy** [comment]
Sure, will do these tonight

**Comment by akashlevy** [comment]
Ok, made the changes:
- I added error messages for when the type is wrong and updated `messages.txt`
- Switched from using `continue` to `else { ... }`
- Split into test cases for `get_noargs` and `get_objrefs`

**Comment by akashlevy** [comment]
Let me know if anything else is needed :)

**Pull request merged**
