### PR TITLE
BUGFIX: Adjust Liberty parser to accept groups with colons

### PR DESCRIPTION
**Pull request by akashlevy**
See issue #114 for more details. Quick (conservative) fix by adding more permissiveness on the group name with `colon_expr` in `liberty/LibertyParse.yy`. Also added the testcase in #114 to check that parsing of the Liberty file doesn't fail.

### CODE REVIEW

**Comment by QuantamHD** [comment]
Does the liberty spec say what's allowed here out of curiosity?

**Comment by QuantamHD** [comment]
I looked through a couple of manuals and it seems like it's left completely unspecified what's allowed in there other than "string". 😞 

https://media.c3d2.de/mgoblin_media/media_entries/659/Liberty_User_Guides_and_Reference_Manual_Suite_Version_2017.06.pdf

I'm guessing pretty much anything is allowed in there other than ( and ).

**Comment by akashlevy** [comment]
(I wish the semiconductor industry would just switch from Liberty to JSON like sane people)

**Comment by QuantamHD** [comment]
(\(#metoo\))

**Comment by akashlevy** [comment]
fixed by a 1 character change in
https://github.com/parallaxsw/OpenSTA/commit/d889f03757d0394cacf1bbdf0b4fb203d4b066f3

Closing

**Pull request closed without merging**
